# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(641, 550)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono Light")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("*{\n"
"    background-color: transparent;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"    border: none;\n"
"    color: #fff;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgba(14, 14, 22, 100);\n"
"    border: 2px solid rgb(24, 24, 36);\n"
"    border-radius: 5px;\n"
"}\n"
"#centralwidget{\n"
"    background-color: rgb(24, 24, 36);\n"
"    text-align: left;\n"
"}\n"
"#footer{    \n"
"    background-color: rgb(9, 5, 13);\n"
"    padding: 10px;\n"
"}\n"
"#messages_widget,\n"
"#menu_widget,\n"
"#right_menu,\n"
"#search_widget,\n"
"#notifications_widget,\n"
"#bottom_menu,\n"
"#login_widget,\n"
"#header_search_widget{    \n"
"    background-color: rgb(9, 5, 13);\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.toolBox_2 = QtWidgets.QToolBox(self.widget)
        self.toolBox_2.setGeometry(QtCore.QRect(180, 0, 250, 550))
        self.toolBox_2.setStyleSheet("QToolBox{\n"
"    background-color: rgb(24, 24, 36);\n"
"    text-align: left;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgba(14, 14, 22, 100);\n"
"    border: 2px solid rgb(24, 24, 36);\n"
"    padding: 10px 5px;\n"
"    border-radius: 5px;\n"
"    text-align: left;\n"
"}\n"
"")
        self.toolBox_2.setObjectName("toolBox_2")
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setGeometry(QtCore.QRect(0, 0, 250, 488))
        self.page_9.setObjectName("page_9")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_9)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.pushButton_6 = QtWidgets.QPushButton(self.page_9)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_11.addWidget(self.pushButton_6)
        self.frame_12 = QtWidgets.QFrame(self.page_9)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_12)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_12.addWidget(self.pushButton_5)
        self.verticalLayout_11.addWidget(self.frame_12, 0, QtCore.Qt.AlignTop)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/chevron-down.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox_2.addItem(self.page_9, icon, "")


        self.page_a = QtWidgets.QWidget()
        self.page_a.setGeometry(QtCore.QRect(0, 0, 250, 488))
        self.page_a.setObjectName("page_a")
        self.verticalLayout_a = QtWidgets.QVBoxLayout(self.page_a)
        self.verticalLayout_a.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_a.setSpacing(0)
        self.verticalLayout_a.setObjectName("verticalLayout_a")
        self.pushButton_a = QtWidgets.QPushButton(self.page_a)
        self.pushButton_a.setObjectName("pushButton_a")
        self.verticalLayout_a.addWidget(self.pushButton_a)
        self.frame_a = QtWidgets.QFrame(self.page_a)
        self.frame_a.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_a.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_a.setObjectName("frame_a")
        self.verticalLayout_b = QtWidgets.QVBoxLayout(self.frame_a)
        self.verticalLayout_b.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_b.setSpacing(0)
        self.verticalLayout_b.setObjectName("verticalLayout_b")
        self.pushButton_b = QtWidgets.QPushButton(self.frame_a)
        self.pushButton_b.setObjectName("pushButton_b")
        self.verticalLayout_b.addWidget(self.pushButton_b)
        self.verticalLayout_a.addWidget(self.frame_a, 0, QtCore.Qt.AlignTop)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/chevron-down.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox_2.addItem(self.page_a, icon, "")


        self.page_10 = QtWidgets.QWidget()
        self.page_10.setGeometry(QtCore.QRect(0, 0, 250, 488))
        self.page_10.setObjectName("page_10")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page_10)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.pushButton = QtWidgets.QPushButton(self.page_10)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_13.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.page_10)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_13.addWidget(self.pushButton_2)
        self.frame_13 = QtWidgets.QFrame(self.page_10)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_13.addWidget(self.frame_13)
        self.toolBox_2.addItem(self.page_10, icon, "")
        self.horizontalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.toolBox_2.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_6.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_5.setText(_translate("MainWindow", "PushButton"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_9), _translate("MainWindow", "Drop Menu 1"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_10), _translate("MainWindow", "Drop Menu 3"))

        self.pushButton_a.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_b.setText(_translate("MainWindow", "PushButton"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_a), _translate("MainWindow", "Drop Menu 2"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
