# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(630, 652)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Mono Light")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("*{\n"
"    background-color: transparent;\n"
"    padding: 0;\n"
"    margin: 0;\n"
"    border: none;\n"
"    color: #fff;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgba(14, 14, 22, 100);\n"
"    border: 2px solid rgb(24, 24, 36);\n"
"    border-radius: 5px;\n"
"}\n"
"#centralwidget{\n"
"    background-color: rgb(24, 24, 36);\n"
"    text-align: left;\n"
"}\n"
"#footer{    \n"
"    background-color: rgb(9, 5, 13);\n"
"    padding: 10px;\n"
"}\n"
"#messages_widget,\n"
"#menu_widget,\n"
"#right_menu,\n"
"#search_widget,\n"
"#notifications_widget,\n"
"#bottom_menu,\n"
"#login_widget,\n"
"#header_search_widget{    \n"
"    background-color: rgb(9, 5, 13);\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setObjectName("toolBox")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 630, 590))
        self.page_3.setObjectName("page_3")
        self.toolBox_2 = QtWidgets.QToolBox(self.page_3)
        self.toolBox_2.setGeometry(QtCore.QRect(140, -10, 250, 550))
        self.toolBox_2.setStyleSheet("QToolBox{\n"
"    background-color: rgb(24, 24, 36);\n"
"    text-align: left;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgba(14, 14, 22, 100);\n"
"    border: 2px solid rgb(24, 24, 36);\n"
"    padding: 10px 5px;\n"
"    border-radius: 5px;\n"
"    text-align: left;\n"
"}\n"
"")
        self.toolBox_2.setObjectName("toolBox_2")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 250, 488))
        self.page_5.setObjectName("page_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_11 = QtWidgets.QPushButton(self.page_5)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/bar-chart-2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_7.addWidget(self.pushButton_11)
        self.frame_10 = QtWidgets.QFrame(self.page_5)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7.addWidget(self.frame_10, 0, QtCore.Qt.AlignTop)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/chevron-down.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox_2.addItem(self.page_5, icon1, "")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 250, 488))
        self.page_6.setObjectName("page_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_6)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pushButton_13 = QtWidgets.QPushButton(self.page_6)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/printer.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_13.setIcon(icon2)
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_9.addWidget(self.pushButton_13)
        self.frame_11 = QtWidgets.QFrame(self.page_6)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9.addWidget(self.frame_11, 0, QtCore.Qt.AlignTop)
        self.toolBox_2.addItem(self.page_6, icon1, "")
        self.toolBox.addItem(self.page_3, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 630, 590))
        self.page_4.setObjectName("page_4")
        self.toolBox.addItem(self.page_4, "")
        self.horizontalLayout.addWidget(self.toolBox)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        self.toolBox_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_11.setText(_translate("MainWindow", "ITEM 2"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_5), _translate("MainWindow", "Drop Menu 1"))
        self.pushButton_13.setText(_translate("MainWindow", "SUB MENU"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_6), _translate("MainWindow", "Drop Menu 2"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "Page 1"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("MainWindow", "Page 2"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
